name: Release

on:
  push:
    tags:
      - "v*" # e.g. v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore workspace cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            dist
            README.md
            LICENSE
            .bun-version
            package.json
          key: workspace-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}-${{ github.event.workflow_run.head_sha }}
          restore-keys: |
            workspace-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}-
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
